# Generated by Django 2.2.5 on 2019-10-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
    ]
